### Practice pytorch tensor problems

In [3]:
import torch
import numpy as np

In [18]:
# 1) Create a numpy array containing 6 random ints in [0,5)
arr = np.random.randint(0,5,6)
arr

array([3, 2, 1, 0, 1, 0])

In [19]:
# 2) Create a pytorch tensor from the array above
x = torch.tensor(arr)
x

tensor([3, 2, 1, 0, 1, 0], dtype=torch.int32)

In [20]:
# 3) Change the dtype from 'int32' to 'int64'
x = x.type(torch.int64)
x.dtype

torch.int64

In [21]:
# 4) Reshape to a 3x2 tensor
x = x.reshape(3,2)
x

tensor([[3, 2],
        [1, 0],
        [1, 0]])

In [22]:
# 5) Return the right-hand column of the tensor
x[:,1:2]

tensor([[2],
        [0],
        [0]])

In [23]:
# 6) Return a tensor of square values without changing the tensor
x.square()

tensor([[9, 4],
        [1, 0],
        [1, 0]])

In [25]:
# 7) Create a new tensor with the same # of elements as the first that can be matrix-multiplied with the first
y = torch.randint(0,5,(2,3))
y

tensor([[0, 4, 0],
        [3, 3, 4]])

In [26]:
# 8) Find the matrix product of the two tensors
x.mm(y)

tensor([[ 6, 18,  8],
        [ 0,  4,  0],
        [ 0,  4,  0]])