In [1]:
import torch
import numpy as np

### Indexing and slicing

In [3]:
x = torch.randint(0,10,(2,3))
x

tensor([[8, 4, 6],
        [6, 0, 9]])

In [4]:
x[1,1]

tensor(0)

In [5]:
x[:,1]

tensor([4, 0])

In [7]:
x[:,1:2]

tensor([[4],
        [0]])

In [10]:
x = torch.randint(0,10,(10,))
x

tensor([4, 8, 8, 2, 9, 3, 8, 9, 0, 7])

In [14]:
# .view() and .reshape() do very similar things. The difference is how they handle the object in memory
x.view(2,5)

tensor([[4, 8, 8, 2, 9],
        [3, 8, 9, 0, 7]])

In [12]:
x

tensor([4, 8, 8, 2, 9, 3, 8, 9, 0, 7])

In [16]:
x.reshape(2,5)

tensor([[4, 8, 8, 2, 9],
        [3, 8, 9, 0, 7]])

In [17]:
x

tensor([4, 8, 8, 2, 9, 3, 8, 9, 0, 7])

In [18]:
x = torch.randint(0,10,(10,))
x

tensor([7, 9, 4, 8, 8, 8, 2, 2, 5, 3])

In [19]:
z = x.view(2,5)
z

tensor([[7, 9, 4, 8, 8],
        [8, 2, 2, 5, 3]])

In [20]:
# Let pytorch infer the other dimension
x.view(2,-1)

tensor([[7, 9, 4, 8, 8],
        [8, 2, 2, 5, 3]])

In [21]:
x.view(-1,5)

tensor([[7, 9, 4, 8, 8],
        [8, 2, 2, 5, 3]])

### Tensor arithmetic

In [26]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
a + b

tensor([[4, 5, 3],
        [5, 5, 5]])

In [27]:
# Underscore arithmetic methods change a tensor in place
print('a before: ', a)
a.add_(b)
print('a after: ', a)

a before:  tensor([[3, 2, 2],
        [1, 3, 3]])
a after:  tensor([[4, 5, 3],
        [5, 5, 5]])


In [29]:
# Element-wise multiplication
a * b

tensor([[ 4, 15,  3],
        [20, 10, 10]])

In [35]:
# Dot product
x = torch.randint(1,3,(3,))
y = torch.randint(1,3,(3,))
print('x: ', x)
print('y: ', y)
print('dot product: ', x.dot(y))

x:  tensor([1, 2, 2])
y:  tensor([1, 1, 2])
dot product:  tensor(7)


In [37]:
# Matrix multiplication
b = b.reshape(3,-1)
print('a: ', a)
print('b: ', b)

a:  tensor([[4, 5, 3],
        [5, 5, 5]])
b:  tensor([[1, 3],
        [1, 4],
        [2, 2]])


In [38]:
torch.mm(a,b)

tensor([[15, 38],
        [20, 45]])

In [43]:
# Euclidian norm (magnitude of 1D vector)
x = torch.randint(1,10,(4,)).type(torch.float32)
x.norm()

tensor(10.6301)

In [44]:
# Get # of els
x.numel()

4

In [47]:
len(x)

4

In [49]:
# len() only gives # of rows for 2D+ tensors!
len(a)

2