In [2]:
import torch
import numpy as np

### Create and manipulate pytorch tensors

In [4]:
# numpy array to pytorch tensor
arr = np.random.randint(0,100,5)
arr

array([43, 41, 87, 45, 40])

In [7]:
x = torch.from_numpy(arr)
x

tensor([43, 41, 87, 45, 40], dtype=torch.int32)

In [8]:
torch.as_tensor(arr)

tensor([43, 41, 87, 45, 40], dtype=torch.int32)

In [9]:
x.dtype

torch.int32

In [10]:
arr2d = np.random.randint(0,100,(4,3))
arr2d

array([[42, 48, 98],
       [30, 81, 59],
       [ 1, 10, 35],
       [61, 37, 26]])

In [11]:
x2 = torch.as_tensor(arr2d)
x2

tensor([[42, 48, 98],
        [30, 81, 59],
        [ 1, 10, 35],
        [61, 37, 26]], dtype=torch.int32)

In [13]:
# There is a relationship between the tensor and the numpy array
arr[0] = 99
print('arr: ', arr)
print('x: ', x)

arr:  [99 41 87 45 40]
x:  tensor([99, 41, 87, 45, 40], dtype=torch.int32)


In [15]:
# To prevent "arr" and "x" from being stored in the same memory location...
new_arr = np.random.randint(0,10,10)
new_tensor = torch.tensor(new_arr)
print('new_arr', new_arr)
print('new_tensor: ', new_tensor)

new_arr [7 5 3 9 9 8 6 7 0 0]
new_tensor:  tensor([7, 5, 3, 9, 9, 8, 6, 7, 0, 0], dtype=torch.int32)


In [16]:
new_arr[0] = 69
print('new_arr', new_arr)
print('new_tensor: ', new_tensor)

new_arr [69  5  3  9  9  8  6  7  0  0]
new_tensor:  tensor([7, 5, 3, 9, 9, 8, 6, 7, 0, 0], dtype=torch.int32)


In [19]:
a = np.array([1,2,3])
x = torch.tensor(a)
x

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
# Creates a floating point tensor
y = torch.Tensor(a)  # same as .FloatTensor()
y

tensor([1., 2., 3.])

### Create pytorch tensor from scratch

In [22]:
# Retain a block of memory allocated to the requested size
torch.empty(2,2)

tensor([[-5.3152e-11,  4.5909e-41],
        [ 0.0000e+00,  0.0000e+00]])

In [24]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones(4,3, dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [28]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [29]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [32]:
tens = torch.tensor([1,2,3])
tens.dtype

torch.int64

In [36]:
tens = tens.type(torch.int32)
tens.dtype

torch.int32

In [37]:
# Creating tensors with random #s
torch.rand((4,3))

tensor([[0.0965, 0.8352, 0.1174],
        [0.7983, 0.8092, 0.4247],
        [0.4845, 0.0750, 0.3381],
        [0.1743, 0.7806, 0.0099]])

In [38]:
torch.randn((3,2))

tensor([[-0.8782, -1.5443],
        [-0.5035, -0.1640],
        [-0.6824, -0.2409]])

In [40]:
torch.randint(0,69,(4,2))

tensor([[48,  3],
        [47, 68],
        [67, 40],
        [ 9, 60]])

In [42]:
x = torch.zeros((2,5))
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [43]:
# Create a new random tensor based on the shape of a previously-defined tensor
torch.rand_like(x)

tensor([[0.6110, 0.7488, 0.3295, 0.1166, 0.6949],
        [0.4913, 0.6215, 0.8357, 0.6136, 0.6796]])

In [44]:
torch.randn_like(x)

tensor([[-0.7660,  0.3616, -2.7721, -0.5640,  0.4192],
        [-0.8725,  0.2691, -0.4505, -0.1882,  0.5806]])

In [46]:
torch.randint_like(x,0,69)

tensor([[ 8.,  7., 40.,  4.,  5.],
        [17., 68., 26., 22., 29.]])

In [47]:
torch.manual_seed(42)
torch.rand((2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])