In [2]:
import numpy as np

# Arrays

### Creating arrays

In [3]:
# Create array from existing object
lst = [1,2,3]
np_array = np.array(lst)
np_array

array([1, 2, 3])

In [4]:
# Transform nested list into numpy array
lst2 = [[1,2,3], [4,5,6], [7,8,9]]
np_arr2 = np.array(lst2)
np_arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Lots of attributes to call on a matrix. Shape is one
np_arr2.shape

(3, 3)

### .arange() - create an array from a range

In [6]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.arange(0,10,2)
b

array([0, 2, 4, 6, 8])

### .zeros() - create an array of zeros

In [8]:
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [9]:
d = np.zeros((4,10))
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### .ones() - create an array of ones

In [10]:
e = np.ones((5,5))
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Operate with a constant on all elements in array
e + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

### .linspace() - create linearly spaced items

In [15]:
f = np.linspace(0,10,3)
f

array([ 0.,  5., 10.])

### .eye() - create an identity matrix

In [16]:
g = np.eye(5)
g

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Create random arrays

### .random.rand(n) - create an array of "n" random #s from a uniform distribution between 0 and 1

In [17]:
h = np.random.rand(4)
h

array([0.58388047, 0.44266814, 0.81201539, 0.07613609])

In [19]:
i = np.random.rand(5,5)
i

array([[0.45964568, 0.28414934, 0.6108939 , 0.32540705, 0.49882823],
       [0.93085064, 0.09974614, 0.82602759, 0.69611616, 0.43017208],
       [0.02747975, 0.50959352, 0.78841847, 0.53428727, 0.96688666],
       [0.45725793, 0.68638797, 0.89976561, 0.4337374 , 0.71799159],
       [0.961953  , 0.39106238, 0.05091823, 0.01921474, 0.36252714]])

### .random.randn(n) - create an array of "n" random #s from a standard normal distribution (mean = 0, std = 1)

In [21]:
j = np.random.randn(4,4)
j

array([[ 0.6037315 ,  1.6909108 ,  0.99067917,  1.08271539],
       [-0.80357204,  1.10983625, -2.19129333,  0.00823938],
       [ 1.26938229,  0.30448249, -2.45393637,  0.61601873],
       [ 1.54453389,  0.29922704,  0.94671593,  0.26378091]])

### .random.randint() - get a random integer

In [23]:
k = np.random.randint(1,100,(5,5))
k

array([[41, 40, 77, 25, 67],
       [71, 84, 21, 93, 16],
       [35, 70, 83, 14, 81],
       [96, 49, 65, 92, 64],
       [38, 34, 86, 85, 24]])

### .random.seed() - standardize results

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
arr = np.arange(25)
rand_arr = np.random.randint(0,50,10)

### .reshape() - change shape of array

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### .max()/.min() - max/min vals of arr

In [29]:
print('max: ', arr.max())
print('min: ', arr.min())

max:  24
min:  0


### .argmin()/.argmax() - index of min/max vals of arr

In [30]:
print('min ix: ', arr.argmin())
print('max ix: ', arr.argmax())

min ix:  0
max ix:  24
