In [1]:
import numpy as np

In [22]:
# 1) Array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# 2) Array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
# 3) Array of 10 5s
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [26]:
# 4) Array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [27]:
# 5) Array of even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [28]:
# 6) 3x3 matrix with vals ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# 7) 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# 8) Random # between 0 and 1
np.random.rand(1)

array([0.42055067])

In [31]:
# 9) Random array of 25 #s sampled from a standard normal distribution
np.random.randn(25).reshape(5,5)

array([[-0.92867036,  0.03219755, -0.67136805, -0.40583285,  0.83226878],
       [ 0.2408331 ,  0.71020113, -1.90767643,  0.19171414,  1.82144243],
       [ 0.00228138, -1.27529678,  0.47680368,  0.18757535,  0.84755778],
       [ 0.66744238, -1.47992534,  0.00684599, -0.38563727,  0.34196506],
       [ 0.82081565,  0.5387406 , -0.47416175, -0.43302738,  0.67081117]])

In [37]:
# 10) 10x10 matrix of values ranging 0.01 to 1
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
# 11) 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# 12) Select bottom-right 3x4 matrix
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [40]:
# 13)  Select the value "20"
mat[3][4]

20

In [41]:
# 14) Select the first 3 elements of the second column
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [44]:
# 15) Select the last row
mat[-1:,]

array([[21, 22, 23, 24, 25]])

In [47]:
# 16) Select the final 2 rows
mat[-2:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
# 17) Sum all values in "mat"
mat.sum()

325

In [50]:
# 18) Get std of all vals in "mat"
mat.std()

7.211102550927978

In [51]:
# 19) Get sum of all cols in "mat"
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [55]:
# Bonus) Set seed to get same random #s
np.random.seed(101)
print('randn: ', np.random.randn(1))
print('rand: ', np.random.rand(1))

randn:  [2.70684984]
rand:  [0.02847423]
