In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Select subset of array
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
# Broadcasting to slice of array still points to original array!    
slice_ = arr[0:6]
slice_

array([0, 1, 2, 3, 4, 5])

In [6]:
slice_[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [8]:
# .copy() - explicitly create a new copy/slice of original array
copy_ = arr.copy()
copy_

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [9]:
# Indexing on 2D arrays
arr_2d = np.random.randint(0,100,(3,3))
arr_2d

array([[ 4,  4, 58],
       [39, 48, 19],
       [92, 80, 14]])

In [10]:
row2 = arr_2d[1]
row2

array([39, 48, 19])

In [12]:
val80 = arr_2d[2][1]
val80

80

In [17]:
# First 2 rows
subarr = arr_2d[:2]
subarr

array([[ 4,  4, 58],
       [39, 48, 19]])

In [19]:
# Sub-matrix
submat = arr_2d[:2,1:]
submat

array([[ 4, 58],
       [48, 19]])

In [20]:
# Conditional selection
arr2 = np.random.randint(0,100,10)
arr2

array([84, 41, 24, 63, 40, 53,  2, 31, 48, 72])

In [21]:
bool_arr = arr2 > 50
bool_arr

array([ True, False, False,  True, False,  True, False, False, False,
        True])

In [23]:
# Return arr2 where bool_arr condition(s) are met
arr2[bool_arr]

array([84, 63, 53, 72])

In [25]:
arr2[arr2 > 50]

array([84, 63, 53, 72])