In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0,100,10)

In [4]:
# Perform operation(s) on all elements of an array
arr + 100

array([164, 141, 156, 116, 133, 106, 175, 178, 178, 194])

In [5]:
# Add array to itself
arr + arr

array([128,  82, 112,  32,  66,  12, 150, 156, 156, 188])

In [8]:
# Divide by 0 throws a warning, not an error!
arr/0

C:\Users\611391\AppData\Local\Temp\1\ipykernel_33824\1489309346.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [10]:
# Square root of array
np.sqrt(arr)

array([8.        , 6.40312424, 7.48331477, 4.        , 5.74456265,
       2.44948974, 8.66025404, 8.83176087, 8.83176087, 9.69535971])

In [11]:
np.log(arr)

array([4.15888308, 3.71357207, 4.02535169, 2.77258872, 3.49650756,
       1.79175947, 4.31748811, 4.35670883, 4.35670883, 4.54329478])

In [12]:
np.sin(arr)

array([ 0.92002604, -0.15862267, -0.521551  , -0.28790332,  0.99991186,
       -0.2794155 , -0.38778164,  0.51397846,  0.51397846, -0.24525199])

In [17]:
arr.sum()

541

In [18]:
arr.mean()

54.1

In [20]:
arr2 = np.random.randint(0,100,(3,4))
arr2

array([[ 1, 10, 16, 65],
       [72, 64, 55, 74],
       [36, 24, 94, 35]])

In [21]:
arr2.sum()

546

In [24]:
# Sum of vals in cols (ACROSS THE ROWS)
arr2.sum(axis=0)

array([109,  98, 165, 174])

In [25]:
# Sum of vals in rows (ACROSS THE COLS)
arr2.sum(axis=1)

array([ 92, 265, 189])